In [1]:
%load_ext autoreload
%autoreload

In [2]:
import pandas as pd

In [3]:
file_path_13579 = "../data/13579_hdr_kvals.txt"

In [4]:
def parse_hdr_kvals(file_path):
    """ parse AR CCOB NB configurations
    """
    content = open(file_path, "r").readlines()
    nb_config_list = []
    for i in range(len(content)):
        one = content[i]
        # RawData/13579/MC_C_20231121_000001/MC_C_20231121_000001_R22_S11.fits
        if one.find('fits')>0:
            if i>0:
                nb_config_list.append(nb_config)
            nb_config = {}
            run_num = one.split('/')[-3]
            day_obs = one.split("_")[2]
            seq_num = one.split("_")[3].strip("/MC")
            #print(day_obs, seq_num)
            nb_config["run"] = int(run_num)
            nb_config["day_obs"] = day_obs
            nb_config["seq_num"] = seq_num
        elif one.find('=')>0:
            tok = one.split("=")[0]
            val = one.split("=")[1].split('\t')[0]
            comment = one.split("=")[1].split('\t')[2]
            #print(tok, val, comment)
            nb_config[tok.strip()] = val
            nb_config[tok.strip()+'_Comment'] = comment
    return nb_config_list

def build_config_df(list_dict):
    """ Make Data Frame from a list of config dicts
    """
    df = pd.DataFrame(list_dict)
    df['Camera_X'] = pd.to_numeric(df['CATKW105'])
    df['Camera_Y'] = pd.to_numeric(df['CATKW107'])
    df['Camera_Z'] = 3.395711882*1000 - pd.to_numeric(df['CATKW109']) # 3.395712 - 0.327662 (carriage-L1S1 plane sep in mm)
    df['Camera_U'] = pd.to_numeric(df['CATKW103'])
    df['Camera_B'] = pd.to_numeric(df['CATKW101'])
    df.head()
    return df

def process_configs(file_path):
    """ Read, parse and make a data frame
    """
    return build_config_df(parse_hdr_kvals(file_path))

def getXYZUB(df, run=13579, day_obs="20231121", seq_num="000001"):
    """ Helper to get useful quantities
    """
    # check that a configuration is found
    if df[ (df['run']==run) & (df['day_obs']==day_obs) & (df['seq_num']==seq_num) ].Camera_X.size>0:        
        X = df[ (df['run']==run) & (df['day_obs']==day_obs) & (df['seq_num']==seq_num) ].Camera_X.item()
        Y = df[ (df['run']==run) & (df['day_obs']==day_obs) & (df['seq_num']==seq_num) ].Camera_Y.item()
        Z = df[ (df['run']==run) & (df['day_obs']==day_obs) & (df['seq_num']==seq_num) ].Camera_Z.item()
        U = df[ (df['run']==run) & (df['day_obs']==day_obs) & (df['seq_num']==seq_num) ].Camera_U.item()
        B = df[ (df['run']==run) & (df['day_obs']==day_obs) & (df['seq_num']==seq_num) ].Camera_B.item()
        return X, Y, Z, U ,B
    else:
        print("No configuration found for:", run, day_obs, seq_num)
        return None

In [5]:
# Process file with list of configurations
df = process_configs(file_path_13579)
df.head()

,run,day_obs,seq_num,CATKW101,CATKW101_Comment,CATKW103,CATKW103_Comment,CATKW105,CATKW105_Comment,CATKW107,...,CATKW126_Comment,CATKW127,CATKW127_Comment,CATKW128,CATKW128_Comment,Camera_X,Camera_Y,Camera_Z,Camera_U,Camera_B
0,13579,20231121,000001,-1.15959,(Camera coord for B axis [deg])\n,-90.0,(Camera coord for U axis [deg])\n,86.561,(Camera coord for X axis [mm])\n,57.6531,...,(CCS x @ surface L3S2 [mm])\n,28.8499,(CCS y @ surface L3S2 [mm])\n,209.284,(Conv test at FP for plan [mm])\n,86.561,57.6531,3068.049882,-90.0,-1.15959
1,13579,20231121,000002,-1.15959,(Camera coord for B axis [deg])\n,-90.0,(Camera coord for U axis [deg])\n,86.561,(Camera coord for X axis [mm])\n,57.6531,...,(CCS x @ surface L3S2 [mm])\n,28.8499,(CCS y @ surface L3S2 [mm])\n,209.284,(Conv test at FP for plan [mm])\n,86.561,57.6531,3068.049882,-90.0,-1.15959
2,13579,20231121,000003,-1.15959,(Camera coord for B axis [deg])\n,-90.0,(Camera coord for U axis [deg])\n,86.561,(Camera coord for X axis [mm])\n,57.6531,...,(CCS x @ surface L3S2 [mm])\n,28.8499,(CCS y @ surface L3S2 [mm])\n,209.284,(Conv test at FP for plan [mm])\n,86.561,57.6531,3068.049882,-90.0,-1.15959
3,13579,20231121,000004,-3.15959,(Camera coord for B axis [deg])\n,-90.0,(Camera coord for U axis [deg])\n,-113.435,(Camera coord for X axis [mm])\n,48.1276,...,(CCS x @ surface L3S2 [mm])\n,-26.6358,(CCS y @ surface L3S2 [mm])\n,303.824,(Conv test at FP for plan [mm])\n,-113.435,48.1276,3069.688882,-90.0,-3.15959
4,13579,20231121,000005,-3.15959,(Camera coord for B axis [deg])\n,-90.0,(Camera coord for U axis [deg])\n,-113.435,(Camera coord for X axis [mm])\n,48.1276,...,(CCS x @ surface L3S2 [mm])\n,-26.6358,(CCS y @ surface L3S2 [mm])\n,303.824,(Conv test at FP for plan [mm])\n,-113.435,48.1276,3069.688882,-90.0,-3.15959

In [6]:
df.tail()

,run,day_obs,seq_num,CATKW101,CATKW101_Comment,CATKW103,CATKW103_Comment,CATKW105,CATKW105_Comment,CATKW107,...,CATKW126_Comment,CATKW127,CATKW127_Comment,CATKW128,CATKW128_Comment,Camera_X,Camera_Y,Camera_Z,Camera_U,Camera_B
75,13579,20231121,000076,4.54611,(Camera coord for B axis [deg])\n,-153.529,(Camera coord for U axis [deg])\n,33.6582,(Camera coord for X axis [mm])\n,-201.895,...,(CCS x @ surface L3S2 [mm])\n,-166.161,(CCS y @ surface L3S2 [mm])\n,239.499,(Conv test at FP for plan [mm])\n,33.6582,-201.895,3065.303882,-153.529,4.54611
76,13579,20231121,000077,4.54611,(Camera coord for B axis [deg])\n,-153.529,(Camera coord for U axis [deg])\n,33.6582,(Camera coord for X axis [mm])\n,-201.895,...,(CCS x @ surface L3S2 [mm])\n,-166.161,(CCS y @ surface L3S2 [mm])\n,239.499,(Conv test at FP for plan [mm])\n,33.6582,-201.895,3065.303882,-153.529,4.54611
77,13579,20231121,000078,4.54611,(Camera coord for B axis [deg])\n,-153.529,(Camera coord for U axis [deg])\n,33.6582,(Camera coord for X axis [mm])\n,-201.895,...,(CCS x @ surface L3S2 [mm])\n,-166.161,(CCS y @ surface L3S2 [mm])\n,239.499,(Conv test at FP for plan [mm])\n,33.6582,-201.895,3065.303882,-153.529,4.54611
78,13579,20231121,000079,-6.2057,(Camera coord for B axis [deg])\n,-206.471,(Camera coord for U axis [deg])\n,-64.9631,(Camera coord for X axis [mm])\n,-217.431,...,(CCS x @ surface L3S2 [mm])\n,-166.556,(CCS y @ surface L3S2 [mm])\n,99.1311,(Conv test at FP for plan [mm])\n,-64.9631,-217.431,3065.977882,-206.471,-6.20570
79,13579,20231121,000080,-6.2057,(Camera coord for B axis [deg])\n,-206.471,(Camera coord for U axis [deg])\n,-64.9631,(Camera coord for X axis [mm])\n,-217.431,...,(CCS x @ surface L3S2 [mm])\n,-166.556,(CCS y @ surface L3S2 [mm])\n,99.1311,(Conv test at FP for plan [mm])\n,-64.9631,-217.431,3065.977882,-206.471,-6.20570

In [7]:
df[(df["seq_num"]=="000012")][["Camera_X", "Camera_Y", "Camera_Z", "Camera_U", "Camera_B"]]

    Camera_X  Camera_Y     Camera_Z  Camera_U  Camera_B
11  -43.7369   113.431  3069.884882    -180.0  -3.15959

In [8]:
# get a CCOB beam config
x, y, z, u, b = getXYZUB(df, run=13579, day_obs="20231121", seq_num="000001")
x, y, z, u, b

(86.561, 57.6531, 3068.0498820000003, -90.0, -1.15959)

In [9]:
import copy
from ghosts.beam import rotate_config_to_ub, concat_dicts
from ghosts.beam_configs import BEAM_CONFIG_0, BEAM_CONFIG_1, BEAM_CONFIG_3

In [10]:
def beam_config_from_data(df, run_id=13579, day_obs="20231121", seq_num="000001"):
    """
    """
    x, y, z, u, b = getXYZUB(df, run_id, day_obs, seq_num)
    print(f'x={x}, y={y}, z={z}, u={u}, b={b}')
    new_beam = copy.deepcopy(BEAM_CONFIG_0)
    new_beam['beam_id'] = day_obs+seq_num
    new_beam['n_photons'] = 100
    new_beam['x_offset'] = y/1000. # 86.561/1000.   # 0.012 # 0.022 # -0.012  # -6.5/1000.
    new_beam['y_offset'] = x/1000. # 57.653/1000. # 0.114 # 0.26  #  0.114  #  100/1000.
    new_beam['z_offset'] = z/1000.  # 3.06
    new_beam = rotate_config_to_ub(new_beam, u, b)
    return new_beam

In [11]:
beam_config_from_data(df, run_id=13579, day_obs="20231121", seq_num="000012")

x=-43.7369, y=113.431, z=3069.8848820000003, u=-180.0, b=-3.15959

{'beam_id': '20231121000012',
 'wl': 5e-07,
 'n_photons': 100,
 'radius': 0.00125,
 'x_offset': 0.113431,
 'y_offset': -0.043736899999999995,
 'z_offset': 3.069884882,
 'z_euler': 180.0,
 'y_euler': -0.7,
 'x_euler': -3.1595899999999633}

In [12]:
beam_configs_13579 = []
for num in range(1, 81):
    seq_num = f'{num:06d}'
    beam_configs_13579.append(beam_config_from_data(df, run_id=13579, day_obs="20231121", seq_num=seq_num))

x=86.561, y=57.6531, z=3068.0498820000003, u=-90.0, b=-1.15959
x=86.561, y=57.6531, z=3068.0498820000003, u=-90.0, b=-1.15959
x=86.561, y=57.6531, z=3068.0498820000003, u=-90.0, b=-1.15959
x=-113.435, y=48.1276, z=3069.688882, u=-90.0, b=-3.15959
x=-113.435, y=48.1276, z=3069.688882, u=-90.0, b=-3.15959
x=-113.435, y=48.1276, z=3069.688882, u=-90.0, b=-3.15959
x=-113.421, y=57.6162, z=3069.805882, u=-90.0, b=-1.15959
x=-113.421, y=57.6162, z=3069.805882, u=-90.0, b=-1.15959
x=-113.421, y=57.6162, z=3069.805882, u=-90.0, b=-1.15959
x=-43.7369, y=113.431, z=3069.8848820000003, u=-180.0, b=-3.15959
x=-43.7369, y=113.431, z=3069.8848820000003, u=-180.0, b=-3.15959
x=-43.7369, y=113.431, z=3069.8848820000003, u=-180.0, b=-3.15959
x=-53.2387, y=113.419, z=3069.967882, u=-180.0, b=-1.15959
x=-53.2387, y=113.419, z=3069.967882, u=-180.0, b=-1.15959
x=-53.2387, y=113.419, z=3069.967882, u=-180.0, b=-1.15959
x=-43.8786, y=-86.5292, z=3067.411882, u=-180.0, b=-3.15959
x=-43.8786, y=-86.5292, z=3067.411882, u=-180.0, b=-3.15959
x=-43.8786, y=-86.5292, z=3067.411882, u=-180.0, b=-3.15959
x=-53.2902, y=-86.5554, z=3067.493882, u=-180.0, b=-1.15959
x=-53.2902, y=-86.5554, z=3067.493882, u=-180.0, b=-1.15959
x=-53.2902, y=-86.5554, z=3067.493882, u=-180.0, b=-1.15959
x=86.549, y=148.149, z=3069.169882, u=-90.0, b=-3.15959
x=86.549, y=148.149, z=3069.169882, u=-90.0, b=-3.15959
x=86.549, y=148.149, z=3069.169882, u=-90.0, b=-3.15959
x=-113.423, y=148.048, z=3070.9248820000003, u=-90.0, b=-3.15959
x=-113.423, y=148.048, z=3070.9248820000003, u=-90.0, b=-3.15959
x=-113.423, y=148.048, z=3070.9248820000003, u=-90.0, b=-3.15959
x=-113.433, y=-42.3531, z=3068.5698820000002, u=-90.0, b=-1.15959
x=-113.433, y=-42.3531, z=3068.5698820000002, u=-90.0, b=-1.15959
x=-113.433, y=-42.3531, z=3068.5698820000002, u=-90.0, b=-1.15959
x=86.5436, y=-42.3147, z=3066.812882, u=-90.0, b=-1.15959
x=86.5436, y=-42.3147, z=3066.812882, u=-90.0, b=-1.15959
x=86.5436, y=-42.3147, z=3066.812882, u=-90.0, b=-1.15959
x=26.4853, y=88.4331, z=3068.958882, u=-180.0, b=-2.15959
x=26.4853, y=88.4331, z=3068.958882, u=-180.0, b=-2.15959
x=26.4853, y=88.4331, z=3068.958882, u=-180.0, b=-2.15959
x=-123.452, y=88.42, z=3070.275882, u=-180.0, b=-2.15959
x=-123.452, y=88.42, z=3070.275882, u=-180.0, b=-2.15959
x=-123.452, y=88.42, z=3070.275882, u=-180.0, b=-2.15959
x=-123.523, y=-61.5583, z=3068.420882, u=-180.0, b=-2.15959
x=-123.523, y=-61.5583, z=3068.420882, u=-180.0, b=-2.15959
x=-123.523, y=-61.5583, z=3068.420882, u=-180.0, b=-2.15959
x=26.4121, y=-61.5395, z=3067.103882, u=-180.0, b=-2.15959
x=26.4121, y=-61.5395, z=3067.103882, u=-180.0, b=-2.15959
x=26.4121, y=-61.5395, z=3067.103882, u=-180.0, b=-2.15959
x=-273.911, y=519.617, z=3076.931882, u=-109.773, b=-20.1578
x=-273.911, y=519.617, z=3076.931882, u=-109.773, b=-20.1578
x=-273.911, y=519.617, z=3076.931882, u=-109.773, b=-20.1578
x=257.179, y=472.57, z=3071.6838820000003, u=-250.227, b=17.9982
x=257.179, y=472.57, z=3071.6838820000003, u=-250.227, b=17.9982
x=257.179, y=472.57, z=3071.6838820000003, u=-250.227, b=17.9982
x=266.114, y=-414.046, z=3060.6368820000002, u=-109.773, b=15.8386
x=266.114, y=-414.046, z=3060.6368820000002, u=-109.773, b=15.8386
x=266.114, y=-414.046, z=3060.6368820000002, u=-109.773, b=15.8386
x=-278.544, y=-448.541, z=3064.994882, u=-250.227, b=-17.4982
x=-278.544, y=-448.541, z=3064.994882, u=-250.227, b=-17.4982
x=-278.544, y=-448.541, z=3064.994882, u=-250.227, b=-17.4982
x=-258.805, y=219.497, z=3073.0858820000003, u=-153.529, b=-8.86529
x=-258.805, y=219.497, z=3073.0858820000003, u=-153.529, b=-8.86529
x=-258.805, y=219.497, z=3073.0858820000003, u=-153.529, b=-8.86529
x=217.21, y=198.78, z=3068.647882, u=-206.471, b=6.7057
x=217.21, y=198.78, z=3068.647882, u=-206.471, b=6.7057
x=217.21, y=198.78, z=3068.647882, u=-206.471, b=6.7057
x=183.769, y=-151.932, z=3064.602882, u=-153.529, b=4.54611
x=183.769, y=-151.932, z=3064.602882, u=-153.529, b=4.54611
x=183.769, y=-151.932, z=3064.602882, u=-153.529, b=4.54611
x=-214.772, y=-167.365, z=3067.912882, u=-206.471, b=-6.2057
x=-214.772, y=-167.365, z=3067.912882, u=-206.471, b=-6.2057
x=-214.772, y=-167.365, z=3067.912882, u=-206.471, b=-6.2057
x=-108.976, y=269.574, z=3072.389882, u=-153.529, b=-8.86529
x=-108.976, y=269.574, z=3072.389882, u=-153.529, b=-8.86529
x=-108.976, y=269.574, z=3072.389882, u=-153.529, b=-8.86529
x=67.0047, y=248.667, z=3070.584882, u=-206.471, b=6.7057
x=67.0047, y=248.667, z=3070.584882, u=-206.471, b=6.7057
x=67.0047, y=248.667, z=3070.584882, u=-206.471, b=6.7057
x=33.6582, y=-201.895, z=3065.303882, u=-153.529, b=4.54611
x=33.6582, y=-201.895, z=3065.303882, u=-153.529, b=4.54611
x=33.6582, y=-201.895, z=3065.303882, u=-153.529, b=4.54611
x=-64.9631, y=-217.431, z=3065.977882, u=-206.471, b=-6.2057
x=-64.9631, y=-217.431, z=3065.977882, u=-206.471, b=-6.2057

In [13]:
beam_configs_df_13579 = concat_dicts(beam_configs_13579)
beam_configs_df_13579.head()

,beam_id,wl,n_photons,radius,x_offset,y_offset,z_offset,z_euler,y_euler,x_euler
20231121000001,20231121000001,5.000000e-07,100,0.00125,0.057653,0.086561,3.068050,-90.0,-1.15959,0.7
20231121000002,20231121000002,5.000000e-07,100,0.00125,0.057653,0.086561,3.068050,-90.0,-1.15959,0.7
20231121000003,20231121000003,5.000000e-07,100,0.00125,0.057653,0.086561,3.068050,-90.0,-1.15959,0.7
20231121000004,20231121000004,5.000000e-07,100,0.00125,0.048128,-0.113435,3.069689,-90.0,-3.15959,0.7
20231121000005,20231121000005,5.000000e-07,100,0.00125,0.048128,-0.113435,3.069689,-90.0,-3.15959,0.7

In [14]:
beam_configs_df_13579.to_parquet("run_13579_beam_configs_v1.parquet")